<?php
namespace Database\Seeders;
use App\Models\Bike; use Illuminate\Database\Seeder;
class DatabaseSeeder extends Seeder { public function run():void { foreach($this->bikes() as $data){$images=$data['images'];$work=$data['work'];unset($data['images'],$data['work']);$bike=Bike::updateOrCreate(['slug'=>$data['slug']],$data);$bike->images()->delete();$bike->workItems()->delete();$bike->images()->createMany($images);$bike->workItems()->createMany($work);} }
private function bikes():array{return [
['name'=>'Trek 7200','slug'=>'trek-7200','brand'=>'Trek','model'=>'7200','type'=>'Hybridsykkel','price'=>2990,'status'=>'Til salgs','size'=>'M','rider_height'=>'ca. 165–178 cm','wheel_size'=>'28 tommer','gears'=>'Shimano 3 × 8','frame'=>'Aluminium','brakes'=>'Felgbremser','color'=>'Mørk grønn','year'=>'Ukjent','description'=>'Lett og allsidig hybridsykkel for jobb, skole, asfalt og grus. En solid hverdagssykkel med oppreist og komfortabel sittestilling.','condition_notes'=>'Normale kosmetiske bruksmerker. Ingen kjente funksjonsfeil etter gjennomgang og prøvekjøring.','featured'=>true,'published_at'=>now(),'images'=>[['path'=>'images/bikes/trek-7200/after-main.jpg','alt'=>'Trek 7200 etter klargjøring','stage'=>'after','sort_order'=>1],['path'=>'images/bikes/trek-7200/before-drive.jpg','alt'=>'Drivverk før rengjøring','stage'=>'before','sort_order'=>2],['path'=>'images/bikes/trek-7200/after-drive.jpg','alt'=>'Drivverk etter rengjøring','stage'=>'after','sort_order'=>3],['path'=>'images/bikes/trek-7200/before-cockpit.jpg','alt'=>'Styre før service','stage'=>'before','sort_order'=>4],['path'=>'images/bikes/trek-7200/after-cockpit.jpg','alt'=>'Styre etter service','stage'=>'after','sort_order'=>5]],'work'=>[['title'=>'Gir og bremser','description'=>'Kontrollert og justert.'],['title'=>'Drivverk','description'=>'Grundig rengjort, smurt og kontrollert for slitasje.'],['title'=>'Hjul og lager','description'=>'Kontrollert og justert ved behov.'],['title'=>'Sikkerhetskontroll','description'=>'Prøvekjørt og sluttkontrollert.']]],
['name'=>'Merida Matts 40','slug'=>'merida-matts-40','brand'=>'Merida','model'=>'Matts 40','type'=>'Terrengsykkel','price'=>2490,'status'=>'Til salgs','size'=>'L','rider_height'=>'ca. 175–187 cm','wheel_size'=>'26 tommer','gears'=>'Shimano 3 × 8','frame'=>'Aluminium','brakes'=>'Skivebremser','color'=>'Sort / sølv','year'=>'Ukjent','description'=>'Robust hardtail til grusvei, tur og variert fritidsbruk.','condition_notes'=>'Pent brukt med noen riper i lakken. Teknisk gjennomgått.','featured'=>true,'published_at'=>now(),'images'=>[['path'=>'images/bikes/merida-matts-40/after-main.jpg','alt'=>'Merida Matts 40 etter klargjøring','stage'=>'after','sort_order'=>1]],'work'=>[['title'=>'Komplett gjennomgang','description'=>'Gir, bremser, drivverk og hjul kontrollert.']]],
['name'=>'DBS Classic','slug'=>'dbs-classic','brand'=>'DBS','model'=>'Classic','type'=>'Bysykkel','price'=>3490,'status'=>'Reservert','size'=>'M/L','rider_height'=>'ca. 168–183 cm','wheel_size'=>'28 tommer','gears'=>'Shimano Nexus 7','frame'=>'Stål','brakes'=>'Felg / fotbrems','color'=>'Blå','year'=>'Ukjent','description'=>'Komfortabel bysykkel med skjermer, bagasjebrett og lukket girsystem.','condition_notes'=>'Kosmetiske bruksspor. Klar til hverdagsturer.','featured'=>false,'published_at'=>now(),'images'=>[['path'=>'images/bikes/dbs-classic/after-main.jpg','alt'=>'DBS Classic etter klargjøring','stage'=>'after','sort_order'=>1]],'work'=>[['title'=>'Sesongklargjøring','description'=>'Rengjort, smurt, justert og prøvekjørt.']]]
];}}
